### ISSUE TITLE
Personatge que es mou pel mapa

### ISSUE THREAD

**Issue by ferranmanya** [EnginyeriaSofwareUB/ES2017B3#2]
En principi no cal que tingui l'aspecte del pollo però estaria mb. Moure's cap als costats, saltar i fer n salts.

Temps aproximat: 4 hores

**Comment by sergigt10** [comment]
- Moviment del personatge (d'esquerra a dreta o salt). Es permet fer un doble salt. 
- Detecció de colisions amb el terra o plataformes.
- Animació del personatge a traves de sprites.
- La càmera segueix el personatge.


Scripts utilitzades: 
	- CameraFollow (seguiment del jugador)
	- PlayerController (Controla els temes de moviment i salts)
	- CheckGround (Controla si el player toca terra o no “Crida script PlayerController”)

2 hores
