### ISSUE TITLE
Un mapa principal gran

### ISSUE THREAD

**Issue by cplanego** [EnginyeriaSofwareUB/ES2017B3#22]
Crear un mapa gran, també les posicions dels equips haurien de ser les correctes,
Temps estimat: 4h
[image](https://user-images.githubusercontent.com/10071569/33489323-db90db80-d6b3-11e7-88bc-e70cf0415c74.png)
Mirar també lo de la carpeta del drive anomenada FONS

**Comment by aescurra** [comment]
Time: 6h

Correciones: fix camera follow, height to dead chicken + 1h
