### ISSUE TITLE
Gestio de so

### ISSUE THREAD

**Issue by cplanego** [EnginyeriaSofwareUB/ES2017B3#26]
A la pantalla principal hi ha que poder gestionar el so de tot el joc, per habilitarlo i deshabilitarlo. 
Temps estimat: 2h

**Comment by TresLos** [comment]
He creat una branca feature/So_i_silenci
Allà està fet el settings, però com que no hi ha el menú (settings), llavors no ho he fet al develop (el merge no funcionava i ho he agut de fer manualment)
- Descobert problema bug de la granada si explota després de canvi de pollastre.
6 a 7 hores de treball (configurar el git, el Unity, arreglant problemes de merge i descobrint com canviar les imatges)

**Comment by TresLos** [comment]
Canviat al menú el control de so
Paral·lelament al boto de sortir

7 hores el primer
5 hores intentant entrar al Unity, 4 hores de feina
Total de 16 hores
